sudo: false
language: ruby
cache: bundler
rvm:
- 2.7.0
branches:
  only:
    - master
    - develop
before_install:
  - export TRAVIS_BUILD_ENV="dev"
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then export TRAVIS_BUILD_ENV="prod"; fi
install:
- echo "$TRAVIS_BUILD_ENV"
- bundle install
- gem install jekyll
script:
- bundle exec jekyll build --config _config.yml,_config_"$TRAVIS_BUILD_ENV".yml
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "M6zgrIA9ybGlpbP5O0CWvP+AjjZ1nDHCao55CuSflvAsmj52agwdJ/OrrZjSaY78gpm3XAjsE7xvgTm0W/KkSZ9WVMHn+WziZi8b+tJ+tGRvr28WWmQW1BILjsupOI7dfSbQUdK0oZfUfwDLcUzpAQjR0NDYlpsS5v3gEwyGhpYsrz2/htpaxnFBeXblweaZTu5A1+wrIHtGzuFA84fUnp9RXnYM8m1nqSYwF1R0Tv6G6/oLmdNg9sTWYLpP50tAQu6KhHMJUgH1RUgaWhchv9p/nwYS9xR/AYHTlQCsFuLGDdElMjg+BnpT3tXH6mA25AlcilVFdmtxlNYLV9nlGN9YhrBnQaRk22fWdax0oNcPwWACvd+miCxPrvwPfZYq0oYx9stnai8fCCvG0CjJY4ql9gT5JzUwTs/UjBInRig3k0qKCX3OdYS6sCMLiw7MQ984KQ9JhdZUpwj+9g+jRtQOP+YeFwRLe12IpBZRNhnnpcMQONpxkwgUvIurKQJynxquSgYhJuNk8sp3hlzR9jEKAewK2gzloPxUlladUmhkoR+CTUme603H/bWoU7C+mtPakHw2sYQkRGfqFJAyer7O1vjIzkMtXwYyD1pJteELmKpMBooKnKBXyJeEzHBAhV8qpC/7ijwZyENmgVfOt1sMk1IWe1XqGX29enTEVcY="
    project: "devezbcme"
    on:
      branch: "develop"
    message: "Deploying to $TRAVIS_BUILD_ENV environment"
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "RYzCnhx6apJk/tf6sKHyyNIEmIIW6QHbaGkOqoUns6QA6zJCOAt5VmbzgJwmeQqUdy5/Eb4d8bifgOychOSOHnxHPiExbZCV381x/LmUa9klcEpeE+Plr0+X1ir9jUQv5KKVWHlItzvKeZYdBAttxX20j5GyA/R/fx1N2JnPXszWB6wgmnkObUKMvNMyfw/QUKVfZytF82JPaBMJ3m3WB0Bxk5YqAKDfxZ4uGIKOAPo5y9bvpvj+/eg5stli9GD7dyNUhHZ5zcrAXJQ57eK4f1+nZfh4BXBharAaDOKvp7dlTn0rZap/BF6mEj6aEpIjyO8QL3X7P0bWh0RSiQxligPbHbzDxOup5ZRp+l0HmVq25Mp9vc7z78a9xaqaB2Sf0Wlkgd0ncGqBhoKtPSpCYunyz/qdpQGZN/4mAOh/QdFYG27KrBV7FGTDSSP/GysW/AbSEtMrLHsPadhfSd8mlJLI0hFXnjeM/Rqw4xKtpk0KxB9OfgTK1qTlpdyFNz6mT+hTZccd82IkilbddskZhvm73WUxXmJP3BjCwkf2y3krHau3tKKq/zzyoGwBOLlMbZRlZd529Ra6Cu29xJuhrWSuBNj30X/ysi97U8CSuGAV1FndZP5ibOx91505/DoTegjUxwEa+W6F984g1WwnjMmkB7+ts8VCzbAa0DiUOeU="
    project: "prodezbcme"
    on:
      branch: "master"
    message: "Deploying to $TRAVIS_BUILD_ENV environment"
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash scripts/clearcache.sh -k "$CF_AUTH_KEY" -e "$CF_AUTH_EMAIL" -z "$CF_ZONE"

