sudo: false
language: ruby
cache: bundler
rvm:
- 2.7.0
branches:
  only:
    - master
    - develop
before_install:
  - export TRAVIS_BUILD_ENV="dev"
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then export TRAVIS_BUILD_ENV="prod"; fi
install:
- echo "$TRAVIS_BUILD_ENV"
- bundle install
- gem install jekyll
script:
- bundle exec jekyll build --config _config.yml,_config_"$TRAVIS_BUILD_ENV".yml
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "tHMbFCPnDizDr0PwlQCj1KGLZn/P7cDEU8C0CEv1Ek5JftZzNZHhEwhpdhORM3plDpb2CN1mlyW0NWwYqXbG06nrj9/fNWKVSGChubclny02hav69uIGHlj420nU+vURWyHK/xQGpgOgEubV6ixATLVD3UieAsXm9wwjM46f3Vs/PTtHkqFTNTX+3Ja0zn9xsnbd6cdIHqUX7MSh74QMuLw8yVVNb+mpTzgy3bLniXKRyPlDTBePZ63MhQpoVGqEufJqQWIGUnX5g8UDfxJ1Rm515/X4RcsTWbuZS+jsrTwcwfBSMwf1uyd2MXtlxkrylErSMXaSieoyBImCJpMu9fnGnT06DKFKMUsVPgmk/Htv2AkhSEwgN8uouj9PHJe/S00cCdW9UuxOGNv8O0mOQCcfx0/P2Z29A4ZRpjvtip6gmk94f+RbzrAhLUUHKOg9DECAsVJqCcjTX/BYqyvC0u4MGU4Zh3namgpjimqCwE/HRWh5+PyMz/2eDb3z7N8Vfb4KqLHhrpkNYEU6ZRFXs9rvJ7IzYhU3CVC3Zb+9wpPSTd2hS6DZXykSIJ4EWKMhBG8fyUZszBHVSyGEqcN7PtGMoNnVr8L3EYq1fYtEDwNEcBB8zTErb1a7mwgqMlC7rAom4vWgIV//TnzaLyVAdqppMMiFLsGCo6t2ZylL4/g="
    project: "devezbcme"
    on:
      branch: "develop"
    message: "Deploying to $TRAVIS_BUILD_ENV environment"
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "WTQd1OPFVe40nJ3HzvTRAkk4GHJUhr87OgEywrZleXg356V+MJvUxY0GR3q9bNLvvH/Uk5jxQwhBs8Q3LVUQSijuMTxqgmxFNM8l9J99/SBIDwKOQzbMz6yPiNOpU5/wmSB4vMZOxcLlY/ilShFzcYgYwpoZrjRjsw/IVNcbXLh/QVI2YcBO2jcfKhxS3rO4l9MLBwK56eqWvatUCa5f3DcQj/wDa9CJu5/AwrQf+6z0JfuDi8v/afQhOh91oviq9bknJoRvHP80Qmwt2AplrdqGusMm+19OSlW64bdxi/70vaeQSP18cKYiIjxDrzIFznw0ZZMR233ZshBqSQNF/cWpOsWQZP4fw0V7Xw+/XIhu2sWPe6Oy4Rxc3FGLK+tzzTaILfChcEQIWjXV6qYrzK+FJnZ6qJUJLtJeDTkq3i1QY7aRWWlwPi0P9FLrJSx74847HOLiKujeGoPtGJLFuuLqMJUHFDZSxH+X/hogD4BZcYAltvr/eFQX+2qOGTuv1q02V/lBM/JWPW37ggWdOuF84nCinavdrU1IQJ0i8s96E4ZHqD64Y5BBu8cYE8iwD0T0EfbMNt610u1ZdDOE4NCGZ04mfyYmH0U+yrKEFGuTOjd+PuyzRpKG1Jlz1pNH8gn66qS6QqmRFgciWktWw/JmdE3v4QOa96JADJAnkLo="
    project: "prodezbcme"
    on:
      branch: "master"
    message: "Deploying to $TRAVIS_BUILD_ENV environment"
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash scripts/clearcache.sh -k "$CF_AUTH_KEY" -e "$CF_AUTH_EMAIL" -z "$CF_ZONE"

